const CLIENT_DANMAKU_RECEIVED = "CLIENT_DANMAKU_RECEIVED"
const CLIENT_CONNECT_SUCCEED = "CLIENT_DANMAKU_SUCCEED"
const CLIENT_CONNECT_FAILED = "CLIENT_CONNECT_FAILED"

module.exports = {
  CLIENT_DANMAKU_RECEIVED,
  CLIENT_CONNECT_SUCCEED,
  CLIENT_CONNECT_FAILED
}